### ISSUE TITLE
Translation initiation analysis

### ISSUE THREAD

**Issue by colin986** [smithlabcode/ribotricer#151]
Hi,

I have Ribo-seq data generated from treatments with Cycloheximide, Harringtonine and a no-drug sample. 

What do you think is the best strategy to use these data with Ribotricer?

I'm thinking to use only the Chx data (110M reads, post QC, post small RNA filtering) to detect ORFs. To determine the TIS for each detected ORF I would move outside of Ribotricer and compare the Harr TIS enrichment vs No drug separately.

To this end, is it possible to generate a merged GTF file containing annotated and novel ORFs

Thanks!
Colin

**Comment by saketkc** [comment]
Ribotricer was designed for non-TIS assays, though in my tests I have found it to be useful for TIS-assays as well. But otherwise, your strategy of using CHX data to detect ORFs (annotated and novel) and then going back to the TIS data to determine the exact start site sounds reasonable.

When you run ribotricer, it first creates an index file which lists down the category of ORF (novel/annotated/utr) along with the location on the genome where these ORFs are. Once you identify ORFs undergoing active translation, you would have to pull out these ORFs and run your TIS-analysis pipeline to determine where the actual starting points are. Does this make sense?
